fix(search-input): change absolute url to relative url
vtexdocs/devportal pull request #102
Opened 2022-12-15 16:27 UTC by melissafalcao

#### What is the purpose of this pull request?

#### What problem is this solving?

#### How should this be manually tested?

#### Screenshots or example usage

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2022-12-15 19:25 UTC, brunoamui requested changes

2022-12-15 19:25 UTC, brunoamui commented on src/components/search-input/functions.ts
> +  const relativeURL = hit.url.replace(/^(?:\/\/|[^/]+)*\//, '')
Acho que conseguimos usar o decodificador nativo de url do javascript para extrair o path mais facilmente. Segundo esse [doc](https://developer.mozilla.org/en-US/docs/Web/API/URL) dá pra vc declarar uma `URL(string)` e usar as funções internas do objeto para extrair o path

2022-12-15 19:26 UTC, brunoamui commented on src/components/search-input/functions.ts
> +  const relativeURL = hit.url.replace(/^(?:\/\/|[^/]+)*\//, '')
Aí tbm n precisaríamos adicionar o `/` no começo do path

2022-12-16 17:01 UTC, leonardoAnjos16 approved these changes
LGTM 💯

2022-12-16 18:50 UTC, merged