New order and fulfillment navigation guides
vtexdocs/devportal pull request #243
Opened 2023-02-15 15:43 UTC by Isabella-Veloso

#### What is the purpose of this pull request?
Reorganize the Developer Portal navigation.

#### What problem is this solving?

#### How should this be manually tested?

#### Screenshots or example usage

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2023-02-16 20:25 UTC, jumeyermattosarruda requested changes

2023-02-16 20:25 UTC, jumeyermattosarruda commented on public/navigation.json
> +              "slug": "orders-feed",
A slug tem que ser o mesmo nome do título do artigo.

2023-02-16 20:25 UTC, jumeyermattosarruda commented on public/navigation.json
> +                  "slug": "integrate-external-orders-vtex-tracking",
A slug tem que ser o mesmo nome do título do artigo. Acho que aqui dá pra diminuir o título do artigo

2023-02-16 20:25 UTC, jumeyermattosarruda commented on public/navigation.json
> +                  "slug": "api-integration",
Acho que pra deixar mais contextual pro MOI, o título e slug podem mencionar MOI, e não só API Integration

2023-02-28 20:11 UTC, Isabella-Veloso commented on public/navigation.json
> +              "slug": "orders-feed",
OK

2023-02-28 20:12 UTC, Isabella-Veloso commented on public/navigation.json
> +                  "slug": "integrate-external-orders-vtex-tracking",
OK

2023-02-28 20:17 UTC, Isabella-Veloso commented on public/navigation.json
> +                  "slug": "api-integration",
OK

2023-03-01 15:00 UTC, jumeyermattosarruda approved these changes

2023-03-01 15:30 UTC, merged