Fix/remove mockup results page
vtexdocs/devportal pull request #331
Opened 2023-04-17 20:40 UTC by RobsonOlv

#### What is the purpose of this pull request?

Add the entire results page.

#### How should this be manually tested?

Go to this page and try to type something in the search bar. Type Enter or click on the option "See all results" (If it isn't appearing, it is because the response returns 7 or fewer hits.)

Once on the search page, try to navigate by pages, select filters and check if the behavior works without problems.

#### Screenshots or example usage

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2023-04-18 15:24 UTC, RobsonOlv commented
> Em uma das pesquisas apareceu que tinha dois resultados, mas só aparece uma página, era pra ser assim mesmo?
> 
> ![image](https://user-images.githubusercontent.com/62757720/232812023-ce49f128-40e0-4b82-bdb5-4fd259e52c90.png)

Por enquanto sim. É porque os dois resultados são da mesma página "_Shipping Simulator_", então eles estão agrupados no mesmo card e podem ser expandidos clicando no ícone no canto superior direito.
Sugeri de posteriormente implementarmos uma lógica de deixar o card, com maior número de hits, expandido quando tiver poucos cards.

2023-04-18 17:07 UTC, aliceoq approved these changes
LGTM

2023-04-25 17:01 UTC, ThayllyR approved these changes
LGTM

2023-04-25 19:57 UTC, brunoamui requested changes
Checar o carregamento da sidebar. Investigar inicia-la já fechada.

2023-05-03 19:45 UTC, ThayllyR approved these changes
LGTM

2023-05-11 14:41 UTC, brunoamui approved these changes

2023-05-11 15:00 UTC, merged